apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      securityContext:
        fsGroup: 33
      containers:
        # Drupal Application Container
        - name: drupal
          image: __IMAGE_URL__/drupal:__IMAGE_TAG__
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "drupal_db" # Should match the DB_NAME variable
            - name: DB_USER
              value: "drupal_user" # Should match the DB_USER variable
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: drupal-persistent-storage
              mountPath: /var/www/html/sites/default/files
          startupProbe:
            tcpSocket:
              host: 127.0.0.1
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30

        # Cloud SQL Auth Proxy Container (Sidecar)
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          args:
            - "--structured-logs"
            - "--port=3306"
            - "__INSTANCE_CONNECTION_NAME__"
          securityContext:
            runAsUser: 0 # Run as root to have permission to listen on a privileged port

        # Adminer Container (Sidecar)
        - name: adminer
          image: __IMAGE_URL__/adminer:__IMAGE_TAG__
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: adminer-sessions
              mountPath: /tmp

      volumes:
        - name: drupal-persistent-storage
          persistentVolumeClaim:
            claimName: drupal-pvc
        - name: adminer-sessions
          emptyDir: {}
